/**
 * optimize-gallery.mjs
 * Converts every photo in assets/gallery/<category>/ into optimized WebP:
 *   assets/gallery-opt/<category>/thumb/  (640px wide, grid cards)
 *   assets/gallery-opt/<category>/full/   (1600px wide, lightbox)
 * and regenerates gallery-data.js (the manifest gallery.js reads).
 *
 * Run whenever photos are added or removed:
 *   npm install sharp   (once)
 *   node scripts/optimize-gallery.mjs
 */
import sharp from 'sharp';
import { readdir, mkdir, writeFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'assets/gallery');
const OUT = path.join(ROOT, 'assets/gallery-opt');

const DIRS = ['sports-day', 'ghana-day', 'character-day', 'others'];
const THUMB_W = 640;
const FULL_W = 1600;

const manifest = {};

// slugify filenames (WhatsApp names have spaces/parens)
function slug(file) {
  return file
    .replace(/\.(jpe?g|png|webp)$/i, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

for (const dir of DIRS) {
  const srcDir = path.join(SRC, dir);
  const thumbDir = path.join(OUT, dir, 'thumb');
  const fullDir = path.join(OUT, dir, 'full');
  await mkdir(thumbDir, { recursive: true });
  await mkdir(fullDir, { recursive: true });

  const files = (await readdir(srcDir)).filter(f => /\.(jpe?g|png)$/i.test(f));
  manifest[dir] = [];

  const BATCH = 6;
  for (let i = 0; i < files.length; i += BATCH) {
    await Promise.all(files.slice(i, i + BATCH).map(async (file) => {
      const src = path.join(srcDir, file);
      const name = slug(file);
      try {
        const meta = await sharp(src, { failOn: 'none' }).metadata();
        const swap = meta.orientation >= 5; // EXIF-rotated portrait
        const w = swap ? meta.height : meta.width;
        const h = swap ? meta.width : meta.height;

        await sharp(src, { failOn: 'none' }).rotate()
          .resize({ width: THUMB_W, withoutEnlargement: true })
          .webp({ quality: 70 })
          .toFile(path.join(thumbDir, name + '.webp'));
        await sharp(src, { failOn: 'none' }).rotate()
          .resize({ width: FULL_W, withoutEnlargement: true })
          .webp({ quality: 78 })
          .toFile(path.join(fullDir, name + '.webp'));

        manifest[dir].push({ n: name, w, h });
      } catch (e) {
        console.error('FAIL', dir, file, e.message);
      }
    }));
    process.stdout.write(`\r${dir}: ${Math.min(i + BATCH, files.length)}/${files.length}   `);
  }
  console.log();
}

await writeFile(
  path.join(ROOT, 'gallery-data.js'),
  '// Auto-generated by scripts/optimize-gallery.mjs — photo manifest with dimensions\n' +
  'var GALLERY_MANIFEST = ' + JSON.stringify(manifest) + ';\n'
);

console.log('Done. Manifest written to gallery-data.js');
